[package]
name = "cc_problems"
version.workspace = true
edition.workspace = true

[dependencies]
coupled_chan = {path = "../coupled_chan"}
hilbert_space = {path = "../hilbert_space", features = ["faer"]}
spin_algebra = {path = "../spin_algebra"}
anyhow = { workspace = true }

serde = {workspace = true}
serde_json = {workspace = true}

cc_qol_utils = { path = "../cc_qol_utils" }
cc_math_utils = {path = "../cc_math_utils"}

rayon = {workspace = true}
indicatif = {version = "0.18", features = ["rayon"]}