[[paths]]
remote_path = "coupled_chan/analysis"
local_path = "analysis"

[[paths]]
remote_path = "coupled_chan/data"
local_path = "data"

[[paths]]
remote_path = "coupled_chan/inputs"
local_path = "inputs"