import numpy as np
from typing import Callable
from enum import Enum

class NumpyInteraction:
    def __init__(self, potential_func: Callable[[float], float]) -> None: ...

class NumpyCoupling:
    def __init__(self, size: int, potential_func: Callable[[float], np.ndarray]) -> None: ...

class Asymptote:
    def __init__(self, l: list[int], matrices: list[np.ndarray], entrance: int) -> None: ...
    
    @staticmethod
    def new_single(l: int, matrix: np.ndarray, entrance: int) -> 'Asymptote': ...

class CollisionWMatrix:
    def __init__(self, asymptote: Asymptote, coupling: NumpyCoupling) -> None: ...

class ScatteringStep:
    def __init__(self, dr_min: float, dr_max: float, dr_ratio: float) -> None: ...
    
    @staticmethod
    def new_single(dr: float) -> 'ScatteringStep': ...
    
    @staticmethod
    def new_transitioned(r_switch: float, step_near: 'ScatteringStep', step_far: 'ScatteringStep') -> 'ScatteringStep': ...

class ScatteringConfig:
    r_start: float
    r_stop: float
    step: ScatteringStep

    def __init__(self, r_start: float, r_stop: float, step: ScatteringStep) -> None: ...

class SCPropagator(Enum):
    LogDerivative = ...
    Numerov = ...

class SValue:
    @property
    def s(self) -> tuple[float, float]: ...
    
    @property
    def a_length(self) -> float: ...
    
    @property
    def cross_sect(self) -> float: ...
    
    @property
    def phase_shift(self) -> float: ...

class SingleChanData:
    mass: float
    energy: float
    l: int
    potential_scaling: float
    scattering_config: ScatteringConfig
    potential: NumpyInteraction

    def __init__(self, mass: float, energy: float, l: int, scattering_config: ScatteringConfig, potential: NumpyInteraction) -> None: ...
    
    def scatter(self, propagator: SCPropagator) -> SValue: ...

    def scatter_dependence(self, propagator: SCPropagator, changes: int, dependence: Callable[[SingleChanData, int], SingleChanData]) -> list[SValue]: ...

class SMatrix:
    def s_matrix(self, i: int, j: int) -> tuple[float, float]: ...
    def entrance_number(self) -> int: ...
    def entrance_momentum(self) -> float: ...
    def momenta(self) -> list[float]: ...
    def scattering_length(self) -> tuple[float, float]: ...
    def elastic_cross_sect(self) -> float: ...
    def inelastic_cross_sect(self) -> float: ...
    def inelastic_cross_sect_to(self, channel: int) -> float: ...
    def cross_sect(self, in_chan: int, out_chan: int) -> float: ...
    def scattering_length_in(self, channel: int) -> tuple[float, float]: ...

class CCPropagator(Enum):
    Johnson = ...
    Manolopoulos = ...
    Numerov = ...

class CoupledChanData:
    mass: float
    energy: float
    scattering_config: ScatteringConfig
    w_matrix: CollisionWMatrix

    def __init__(self, mass: float, energy: float, scattering_config: ScatteringConfig, w_matrix: CollisionWMatrix) -> None: ...
    
    def scatter(self, propagator: CCPropagator) -> SMatrix: ...

    def scatter_dependence(self, propagator: CCPropagator, changes: int, dependence: Callable[[CoupledChanData, int], CoupledChanData]) -> list[SMatrix]: ...
