[package]
name = "li2_feshbach"
version.workspace = true
edition.workspace = true

[dependencies]
cc_problems = { workspace = true }

[dev-dependencies]
math_utils = { path = "../../crates/math_utils" }