[package]
name = "hilbert_space"
version.workspace = true
edition.workspace = true

[dependencies]
cc_matrix_utils = {path = "../cc_matrix_utils"}

dyn-clone = "1.0"
downcast-rs = "2.0"
num-traits = {workspace = true}

faer = { workspace = true, optional = true}
nalgebra = { workspace = true, optional = true}
ndarray = { workspace = true, optional = true}

serde = {workspace = true}
[features]
faer = ["dep:faer", "cc_matrix_utils/faer"]
nalgebra = ["dep:nalgebra", "cc_matrix_utils/nalgebra"]
ndarray = ["dep:ndarray", "cc_matrix_utils/ndarray"]
