[package]
name = "coupled_chan_cli"
version.workspace = true
edition.workspace = true

[dependencies]
clebsch-gordan = { workspace = true }
clap = { version = "4.6", features = ["derive"] }
serde = {workspace = true}
serde_json = {workspace = true}
json_comments = "0.2"
toml = "1.1"
json5 = "1.3"
anyhow = {workspace = true}
# libloading = "0.9"
cc_problems = {path = "../cc_problems"}
coupled_chan = {path = "../coupled_chan"}
cc_qol_utils = {path = "../cc_qol_utils"}