[package]
name = "single_chan"
version.workspace = true
edition.workspace = true

[dependencies]
constants = {path = "../constants"}
propagator = {path = "../propagator"}
num-complex = {workspace = true}
math_utils = {path = "../math_utils"}